title: "Shugavaneshwar"
logo: assests/profile_photo.jpeg

# This will show on the LEFT side under the profile photo
description: |
  Check out my projects on <a href="https://github.com/NickStrain" target="_blank">GitHub</a>.

theme: jekyll-theme-minimal
show_downloads: false   # removes GitHub logo button

# disable github button
github: false


